In [4]:
import numpy as np
import pandas as pd
import plotly.graph_objs as go
import plotly
import json
from sqlalchemy import create_engine

In [2]:
df = pd.DataFrame({'x': x, 'y': y})
group = ['group-1','group-2','group-3']

for i in group:
    N = 40
    x = np.linspace(0,1,N)
    y = np.random.rand(N)
    df_temp = pd.DataFrame({'x': x, 'y': y})
    df_temp['group'] = i
    
    
print(x)
print(y)
df.head(5)

[0.         0.02564103 0.05128205 0.07692308 0.1025641  0.12820513
 0.15384615 0.17948718 0.20512821 0.23076923 0.25641026 0.28205128
 0.30769231 0.33333333 0.35897436 0.38461538 0.41025641 0.43589744
 0.46153846 0.48717949 0.51282051 0.53846154 0.56410256 0.58974359
 0.61538462 0.64102564 0.66666667 0.69230769 0.71794872 0.74358974
 0.76923077 0.79487179 0.82051282 0.84615385 0.87179487 0.8974359
 0.92307692 0.94871795 0.97435897 1.        ]
[0.40152907 0.66225716 0.15632899 0.10031075 0.62673712 0.63815678
 0.04929945 0.11543356 0.18896346 0.21368743 0.45556597 0.59671725
 0.78008576 0.07442546 0.0154139  0.7314266  0.46842989 0.12678015
 0.28600219 0.49165832 0.26862232 0.81115354 0.19125645 0.98550553
 0.23867198 0.7321824  0.71959288 0.67322567 0.70751876 0.47752767
 0.37800153 0.84324025 0.89368139 0.88281376 0.30797208 0.28596377
 0.59993092 0.70749968 0.75103561 0.34746029]

          x         y
0  0.000000  0.401529
1  0.025641  0.662257
2  0.051282  0.156329
3  0.076923  0.100311
4  0.102564  0.626737

In [7]:
engine = create_engine('sqlite:///' + "../data/test.db")
df.to_sql('Dummy', engine, index=False, if_exists='replace')

In [5]:
data = [
    go.Bar(
        x = df['x'],
        y = df['y']
    )
]

graphJSON = json.dumps(data, cls=plotly.utils.PlotlyJSONEncoder)
graphJSON

'[{"x": [0.0, 0.02564102564102564, 0.05128205128205128, 0.07692307692307693, 0.10256410256410256, 0.1282051282051282, 0.15384615384615385, 0.1794871794871795, 0.20512820512820512, 0.23076923076923075, 0.2564102564102564, 0.28205128205128205, 0.3076923076923077, 0.3333333333333333, 0.358974358974359, 0.3846153846153846, 0.41025641025641024, 0.4358974358974359, 0.4615384615384615, 0.48717948717948717, 0.5128205128205128, 0.5384615384615384, 0.5641025641025641, 0.5897435897435898, 0.6153846153846154, 0.641025641025641, 0.6666666666666666, 0.6923076923076923, 0.717948717948718, 0.7435897435897436, 0.7692307692307692, 0.7948717948717948, 0.8205128205128205, 0.8461538461538461, 0.8717948717948718, 0.8974358974358974, 0.923076923076923, 0.9487179487179487, 0.9743589743589743, 1.0], "y": [0.4015290704008043, 0.6622571637074229, 0.15632898620869662, 0.10031074570394505, 0.6267371196393017, 0.6381567814068302, 0.04929945014375825, 0.1154335572475802, 0.18896346361352434, 0.21368742638119909, 0.45556596728119403, 0.5967172544814546, 0.7800857566739984, 0.07442545805605827, 0.015413902133566859, 0.7314265998473936, 0.4684298922330893, 0.12678014549670436, 0.2860021877192682, 0.49165831925129666, 0.26862231782133184, 0.8111535444061457, 0.19125645233559485, 0.9855055296280657, 0.238671976138091, 0.7321823990879616, 0.7195928772082502, 0.6732256655585686, 0.7075187634816217, 0.47752766870219654, 0.3780015290246844, 0.8432402502964047, 0.8936813914090445, 0.8828137556231218, 0.30797208137101073, 0.2859637694573184, 0.5999309195295185, 0.7074996844736787, 0.7510356072912325, 0.34746029227489383], "type": "bar"}]'